version: '3.2'
services:
  postgres:
    image: postgres:9.6
    hostname: postgres
    container_name: postgres-saga
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=saga
      - POSTGRES_USER=saga
      - POSTGRES_PASSWORD=password

  elasticsearch:
    image: elasticsearch:6.6.2
    hostname: elasticsearch
    container_name: elasticsearch-saga-akka
    environment:
      - "ES_JAVA_OPTS=-Xmx256m -Xms128m"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300

  alpha-server-1:
    image: coolbeevip/servicecomb-pack
    hostname: alpha-server-1
    container_name: alpha-server-1
    ports:
      - 8081:8080
      - 8091:8090
    environment:
      - "spring.profiles.active=prd"
      - "spring.datasource.url=jdbc:postgresql://postgres:5432/saga?useSSL=false"
      - "spring.datasource.username=saga"
      - "spring.datasource.password=password"
      - "spring.data.elasticsearch.cluster-name=docker-cluster"
      - "spring.data.elasticsearch.cluster-nodes=elasticsearch:9300"
      - "alpha.cluster.master.enabled=true"
      - "alpha.feature.akka.enabled=true"
      - "alpha.feature.akka.transaction.repository.type=elasticsearch"      
    links:
      - postgres:postgres
      - elasticsearch:elasticsearch
    depends_on:
      - postgres
      - elasticsearch
  alpha-server-2:
    image: coolbeevip/servicecomb-pack
    hostname: alpha-server-2
    container_name: alpha-server-2
    ports:
      - 8082:8080
      - 8092:8090
    environment:
      - "spring.profiles.active=prd"
      - "spring.datasource.url=jdbc:postgresql://postgres:5432/saga?useSSL=false"
      - "spring.datasource.username=saga"
      - "spring.datasource.password=password"
      - "spring.data.elasticsearch.cluster-name=docker-cluster"
      - "spring.data.elasticsearch.cluster-nodes=elasticsearch:9300"
      - "alpha.cluster.master.enabled=true"
      - "alpha.feature.akka.enabled=true"
      - "alpha.feature.akka.transaction.repository.type=elasticsearch"      
    links:
      - postgres:postgres
      - elasticsearch:elasticsearch
    depends_on:
      - postgres
      - elasticsearch
      